language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install: "pip install testingbotclient"

# command to run tests
script: python test_travis.py

env:
  global:
  - secure: v2ePLU6gnaevK+0gdWAVVZZ4Wa11raLZgpLHQGzYY2i2k2uvlJi70Mtp8nO41MxVjDq7bWz1Vt7KpYUxFM2tdnZGYUDE07DLqJk3T3mwb5iekgF0JoJ9bYlnr5jHf2taREG4TpTHJ1eCMxFK0I8y3c3jVddnzk3MEnOtSvSSo9x0Vp2rZZb4x6kKVV9KBFDswl3foLv5oYCMI+uZHZdlW1bST92bRrZMvhSl60hpguoJJUSlx7v8dsS0i2QseEUHFZkRL3ZzklOs1Fg5Y93Gyxs64suvInaM8cAl+5MtC7Zi39iQktuSD+Hc6tNoeZsEbEqxtToUJASE3twpsQYHJQ3RSQM0Hbpz4Zg9Oy4Fb2JCvalk5Klx4QeSqTDSKWN67oDSS+tiVawZNgfABXlip2JFCCMlKvVtdfDQ5Ow8iH/5h5YwSTO9hAsb8f5DmBLY5J8iMGkT+b1Ou/R5HfhAcmmh+nhNbtiA9Q/iwca6wfQNvRZmTVIEfd/hgNpiaqR2+TuaVj3NrjvPS6Hx1waJQ5lvwnUewknMyX4WqnQeVKacCj69tTeLY3gXptHPDLxoZvDgNtpR9POJ5FyR6qqiq6OLkMTwLBTr72/F7u5lJ9W+JVPMCnXbRUw24NDGXA7X4tyyp/kagOyFrtGhctMtwgBoZmmpxVqx8Twr+pAQ9yk=
  - secure: h1eEgv7cw2Iv4tCPLosF5tY7Y6kU+1EOCq7f9Fomb4VqUw1wFwAE+Shgw87G/9zDb0uY0mP6lE6S8VLsolBqgF+aWqP8YmJ1mv2XljTzKR5vGgBJJtz2QAozcGP8lGBGlUJipU9DNPS18oFSgAF/cUuExi636jsO5z6mmzNncvoXyLPQeeE1iww/0/KcRUpMVkaQbK9uoWq70kAw0OHy2b0pXl0cbKKAl2x2TswPKy79Xav/zyk3yB9DAippbqYYqbjH+rzgv74LInjgCDaXWhxHBJ21xbd7EClnj4B1tyR2ZNmMQwGDExA4pwt1W+gpp25icmBG1/bKwAVKUCyeKQ48iOKoNoujgwJ/e3k3tlnk7fJtf8vtCpvUdf0ErowyUSVPWkwJI6SRybJTE4wb61RHbh5j1lMrsORai1d664gE1ChV4ELAx2ECDxrL5JmfETHmTG8/JEmbR8VZSH1Hl9S+uFbSokXivBpdHGfXi4csydPJq/fnjxKK0pvm8BoXsajirkhBzNVHMSKSK/e7PGr9jCvPPqXb4htp3CCJZop466PQ5nvxtb3bRilTvD2k8sbNxKTEfhDXQnZ1/fecJbyP9DS2UznyP7+AUXTY4xb7OAf0Ga/r1tVG/CZFkBS2O50zLOil56Gk+265T4t7960Uf/nO83pOnVOEK3Js524=